### ISSUE TITLE
Track Individual's Locations

### ISSUE THREAD

**Issue by thelmuth** [lspector/Clojush#109]
In order to efficiently gather ancestry info, I suggest adding `location` and `parent-locations` to individuals. The `location` will just be the individual's index in the population, where `parent-locations` will be a vector containing the individual's parents' indices in the population.

**Comment by Vaguery** [comment]
Seconded.

Actually, I am surprised that they don't have unique IDs already, and record links to their "parents". Wouldn't that be more generally useful than locations, especially when I do something reasonable like turn off lock-step generations?

**Comment by thelmuth** [comment]
Yup, this seems like a good idea. I think I'm going to go with UUID (v4) for IDs, and also add a vector of parent IDs (since in Clojush an individual can have 1, 2, or more parents), as well as the genetic operator(s) that created it.

**Comment by Vaguery** [comment]
Don't be surprised (as I was when I went with UUID) how ridiculously _long_ they are.

**Comment by thelmuth** [comment]
eh, yeah, that's what you pay for when you want unique IDs I guess.

**Comment by Vaguery** [comment]
Is this maybe done?
