### ISSUE TITLE
How do I record multiple "errors" for one I/O pair?

### ISSUE THREAD

**Issue by Vaguery** [lspector/Clojush#142]
I'm building a few of my nasty test suite of problems, mainly to get a better hands-on feel for actually writing them from scratch and running them.

In at least one case, the desired result is an integer, and I want to minimize _both_ the number of digits in the integer and the number of non-01 digits. How would I go about writing `:error-function` to do that?

**Comment by thelmuth** [comment]
Many of the problems in [clojush.problems.software](https://github.com/lspector/Clojush/tree/master/src/clojush/problems/software) do this. For example, see X-Word Lines: https://github.com/lspector/Clojush/blob/master/src/clojush/problems/software/x_word_lines.clj#L143

The key is that the error function just has to return a vector of errors -- it's not necessary to have 1 error per test case. So, what I do is make a vector of errors for each test case, stick them all into a vector, and then flatten the vector containing all those vectors of errors.

**Comment by Vaguery** [comment]
Thanks!
