### ISSUE TITLE
Dependencies in project.clj seem out of date?

### ISSUE THREAD

**Issue by Vaguery** [lspector/Clojush#157]
I note [this](https://github.com/lspector/Clojush/blob/master/project.clj#L7) sets it up to use only clojure 1.5.1, and later on the midje dependency is out of date as well. I've been using 1.7 in all my recent work, and I'm concerned some functionality may be missing as a result. I really don't know which if any of the other packages might also be running behind.

Is there a "best practice" for keeping these up to date when managing a clojure project like this?

**Comment by lspector** [comment]
I don't know about best practices on this but if someone wants to update the dependencies in project.clj and do enough testing to catch any obvious problems then I'd be happy to merge it into master.

**Comment by Vaguery** [comment]
dibs

**Comment by Vaguery** [comment]
Could you be more specific than "do enough testing to catch any obvious problems"?

Like load and run some examples? Make sure it runs the advanced super-new undocumented stuff? This is in service of actually automating the testing itself, so it's not exactly obvious.

**Comment by Vaguery** [comment]
I've made sure all the things I typically run here still run as expected. You'll have to let me know what, if anything, breaks under stress, but these are all stable releases so they should be compatible.

**Comment by lspector** [comment]
> Could you be more specific than "do enough testing to catch any obvious problems"?
> Like load and run some examples? Make sure it runs the advanced super-new undocumented stuff? This is in service of actually automating the testing itself, so it's not exactly obvious.

Yeah, I meant load and run some examples. I'd personally run my own "advanced super-new undocumented stuff" (`:autoconstructive true`), but I'm not sure how bewildering an experience that would be for someone else. I appreciate that doing it *correctly* is not obvious, and defer to you on what questions/answers come down that path.

**Comment by Vaguery** [comment]
Hopefully with diligence and salesmanship this whole painful process will make it trivial for you to write automated tests to check—in a matter of seconds—that any single change you make, even the fancy new ones, break no existing functionality.

**Comment by Vaguery** [comment]
Fixed in #158

**Comment by Vaguery** [comment]
I am moving my dev folder to a new machine, and to get Clojush to run (fresh Java and `lein` installs) I had to update the `cider` dependency in the project to the current `0.21.0`. I have not checked the dependencies since then, but I am wondering why you're not using stable Clojure 1.10.0 among other things.
