### ISSUE TITLE
Deploy tags to clojars

### ISSUE THREAD

**Issue by saulshanabrook** [lspector/Clojush#166]
We want to help lee with doing releases. This is how releases work:

0. Generate a new version number
1. Update some files with new version
2. Add git commit for this version
3. Add git tag to this version
4. Push these to github
5. deploy the code to clojar

We could easily tackle 6 through travis.

The other steps are a bit more complicated. It is certainly possible to do all of that in Travis, it is just a matter of figuring it when/how we want to do it all. 

For example, we could bump the version after every commit to master automatically. The problems I see with this are:

1. How does it know whether to do a minor or major bump? Maybe just have minor bump by default then some way to enable major bump
2. We have to be weary of race conditions here... For example, let's say travis pulls a commit and all tests pass, and then it goes to add a new version commit and push that. But what if someone else pushes a new commit halfway through that process. Then travis wont be able to cleanly push the bump version commit. Maybe that is fine, since it wont happen very often, but just something to think about.
3. I am not sure if you want to bump a new version after every single commit

We would store credentials securely in the travis CI file and pick them up like this: https://github.com/technomancy/leiningen/blob/master/doc/DEPLOY.md#credentials-in-the-environment.

**Comment by Vaguery** [comment]
Please make sure to add a gatekeeper item "Make sure all Midje tests pass"

**Comment by saulshanabrook** [comment]
@Vaguery Will `lein test` cover that?

**Comment by Vaguery** [comment]
@saulshanabrook Nope, at least not until we finish making the change over to encapsulated interpreter. At present running `lein midje` will attempt to load all source and test code (because many smart programmers include tests in place in their codebases), and `lein test` will not run the `midje` tests. So it can wait. Just leave room for it, as future proofing.

**Comment by saulshanabrook** [comment]
Fixed in #174
