### ISSUE TITLE
Run Midje in Travis

### ISSUE THREAD

**Issue by saulshanabrook** [lspector/Clojush#182]
Travis should run the Midje tests properly. This is blocked on marick/Midje#345

**Comment by Vaguery** [comment]
You can use `lein midje` and it will run them all once. The `:autotest` flag starts a watcher daemon that will re-run them whenever a file is saved.

If finer control is needed, consider adding [midje tags](https://github.com/marick/Midje/wiki/Using-metadata-to-filter-facts) to turn off the slow or resource-intensive tests. (See the way I've labeled some facts in [this extremely slow namespace](https://github.com/Vaguery/push-in-clojure/blob/master/test/acceptance/stress_tests.clj) with both `:slow` and `:acceptance`. To run them (which I only intend to do when I have made a deep change to the interpreter behavior or added a big blob of new instructions and types) I use `lein midje :filter slow` or `lein midje :filter acceptance`.

**Comment by saulshanabrook** [comment]
@Vaguery But how do I tell lein midje to run all tests under the `test` directory?

**Comment by Vaguery** [comment]
See [this rtfm page](https://github.com/marick/Midje/wiki/Lein-midje): `lein midje project.*`, with the initial `test` part implicit I guess.

```text
lein midje clojush.midje.*
128
All checks (70) succeeded.
tmesis:Clojush bill$ lein midje clojush.test.*
>>> Output from clojure.test tests:

0 failures, 0 errors.
>>> Midje summary:
All checks (1) succeeded.
tmesis:Clojush bill$ lein midje clojush.test.* clojush.midje.*
128
>>> Output from clojure.test tests:

0 failures, 0 errors.
>>> Midje summary:
All checks (71) succeeded.
```

**Comment by Vaguery** [comment]
I suspect a lot of the stuff I added should _not_ be part of the canonical Clojush distribution. I think maybe I might have introduced a bug when I used vectors in my stuff, which are almost certainly bad somehow in the Clojush context.

**Comment by saulshanabrook** [comment]
Yeah I saw I could do that, but that is based on namespaces not file paths. It works though.

**Comment by saulshanabrook** [comment]
I am closing this because there aren't enough tests right now to make running on travis a priority
