### ISSUE TITLE
auto-simplification does not work as expected

### ISSUE THREAD

**Issue by Vaguery** [lspector/Clojush#251]
I am writing up my experiences using Clojush to run `/Clojush/src/clojush/problems/demos/simple_regression.clj`, and was able to evolve a program that worked fine. However, the auto-simplified program does _not_ match the behavior, even though it reports `errors: (0 0N 0N 0N 0N 0N 0N 0N 0N 0N)`.

This seems to be a bug.

**Comment by Vaguery** [comment]
For reference, it simplified

```
(in1 integer_mult integer_add 9 integer_sub in1 integer_div 7 3 4 integer_div integer_div integer_mult 4 integer_div integer_div integer_mult integer_mult integer_add in1 integer_add in1 in1 integer_mult integer_sub integer_sub in1 1 in1 integer_mult integer_div in1 integer_sub integer_mult integer_mult integer_div in1 integer_sub integer_mult integer_div integer_mult integer_div in1 integer_sub integer_mult integer_div integer_sub integer_mult)
``` 
(confirmed to be y=x^3 - 2x^2 -x) to 

```
(3 4 integer_div in1 integer_add in1 integer_mult integer_sub in1 1 in1 integer_mult integer_div in1 integer_sub integer_mult in1 integer_sub in1 integer_sub)
```

which is definitely not the same thing.

**Comment by lspector** [comment]
This is from the autosimplification that is performed automatically at the end of a run?

**Comment by Vaguery** [comment]
Yes, but it turns out it was just that the demo file pushes the bloody value to both `:input` and `:integer`.
