### ISSUE TITLE
number is a bad name for a function

### ISSUE THREAD

**Issue by thelmuth** [lspector/Clojush#253]
I feel like the `number` function's name has two major problems:

1. It's entirely unclear what it does.
2. It makes me worry that it will collide with the same name from somewhere else (recall the `state` debacle of 2012(?)

Could we call it something like `number-or-random-element`?

https://github.com/lspector/Clojush/blob/904a92397b99100bf983a7d7adbcbc50a119bb4b/src/clojush/pushgp/genetic_operators.clj#L11

**Comment by lspector** [comment]
Agreed it's a bad name. Happy for it to change. Not crazy about `number-or-random-element` either, but can't immediately think of anything better.... maybe `number-from-number-or-collection`? That'd be even longer but more clear, I think.

**Comment by thelmuth** [comment]
While your name is clearer in intent, I think `number-or-random-element` is closer to what it actually does. It doesn't at all make sure that the randomly selected thing from the collection is a number.

That said, I'm perfectly happy with either one, and much more so than `number`.

**Comment by lspector** [comment]
Okay -- change it however you think is best!
