### ISSUE TITLE
Possible minor bug?

### ISSUE THREAD

**Issue by thelmuth** [lspector/Clojush#285]
Is this supposed to be `(use-type :exec)`, not `(use-type :integer)`?

https://github.com/lspector/Clojush/blob/6eb09bc9979b165c288d5d0dd8fdfe8bd293439f/src/clojush/args.clj#L1043

I'm not really sure what this code does, and if it is a small deal or big deal if it is a bug.

**Comment by lspector** [comment]
Yes! I believe this is a bug. Good catch!

Affects nothing if you don't use tag-enrichment.

But if you do use tag-enrichment, then the enrichment will be a little wrong. While the regular tag/untag/tagged instructions will be enriched correctly, the "reified" tag instructions, which take tags from the integer stack, won't be enriched for tagging things on the exec stack, and will be double enriched for tagging things on the integer stack.

Could you make a pull request for the fix here?
